NumPy (short for Numerical Python) is the foundational open-source library for numerical and scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-performance mathematical functions to operate on them efficiently.

Nearly the entire Python data science ecosystem—including Pandas, SciPy, Scikit-learn, PyTorch, and TensorFlow—is built on top of NumPy.

In [2]:
import numpy as np
a=np.arange(10,15)
a

array([10, 11, 12, 13, 14])

In [3]:
b=np.arange(10,50,4)
b

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

In [5]:
np.var(a)
np.var(b)

np.float64(132.0)

In [6]:
np.mean(a)

np.float64(12.0)

In [7]:
np.mean(b)

np.float64(28.0)

In [8]:
np.std(a)

np.float64(1.4142135623730951)

In [9]:
np.std(b)

np.float64(11.489125293076057)

In [10]:
a

array([10, 11, 12, 13, 14])

In [11]:
np.median(a)

np.float64(12.0)

In [12]:
np.median(b)

np.float64(28.0)

In [19]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(3,5)

array([[0.29042883, 0.27596164, 0.31918193, 0.93989329, 0.90236831],
       [0.68231846, 0.19836938, 0.00652082, 0.67033967, 0.36062474],
       [0.97867617, 0.98087831, 0.72928926, 0.67115055, 0.26416984]])

In [ ]:
np.random.rand(100,4)#generating uniformly distributed random numbers b/w 0 to 1

array([[0.55301065, 0.88802734, 0.8530644 , 0.25432008],
       [0.1678943 , 0.73114837, 0.94312553, 0.84900233],
       [0.92675339, 0.05188338, 0.62899122, 0.85976235],
       [0.51563346, 0.82364351, 0.18686437, 0.53259309],
       [0.3686384 , 0.36947848, 0.7950495 , 0.42636079],
       [0.62133477, 0.09596156, 0.981909  , 0.71888761],
       [0.02322669, 0.19081606, 0.83666394, 0.26890613],
       [0.52745023, 0.99026782, 0.86627385, 0.65712019],
       [0.74296558, 0.07208774, 0.3451572 , 0.64460404],
       [0.08410305, 0.40721483, 0.21410931, 0.36222962],
       [0.56446668, 0.39825852, 0.25429888, 0.51200263],
       [0.75649304, 0.49297577, 0.37530263, 0.21722693],
       [0.42037331, 0.87045665, 0.17210937, 0.77689959],
       [0.28976484, 0.24479605, 0.70114475, 0.6886163 ],
       [0.35168817, 0.54695827, 0.46558422, 0.80609154],
       [0.22629774, 0.08543417, 0.10571158, 0.48562216],
       [0.82645235, 0.37674579, 0.11793194, 0.86386646],
       [0.28102843, 0.3033798 ,

In [ ]:
np.random.randn(100,4) #Generating random of numbers of standard normal distribution

array([[ 6.29773523e-01,  1.13549354e+00,  1.39945201e+00,
        -9.35760960e-01],
       [ 1.99588704e+00, -1.40799040e-01, -8.08492272e-01,
         7.04074554e-02],
       [ 4.30355440e-01, -8.80115101e-01,  1.55297759e+00,
         1.47574671e+00],
       [ 1.01431442e+00,  7.58227423e-01,  8.27229424e-01,
        -9.01226612e-02],
       [ 1.00050504e+00, -1.90564290e+00,  1.13942387e+00,
        -4.01051568e-01],
       [-1.24043385e+00,  1.11757160e+00, -7.95776201e-01,
         2.51689693e-01],
       [-1.53815742e+00, -7.48754043e-01, -1.71854895e+00,
        -8.51161261e-01],
       [-5.66101884e-01,  7.88094804e-01,  1.02668147e+00,
        -1.59679566e+00],
       [-5.10888913e-01,  8.58058285e-01, -6.92985875e-01,
         3.79664454e-01],
       [-2.65186183e-01, -8.90472116e-01,  2.07306998e-01,
        -1.04751772e+00],
       [-2.32228079e+00,  1.14450362e+00,  2.03168301e-01,
        -3.26489476e-01],
       [ 9.50650419e-01, -9.94387582e-01,  1.18649022e-01,
      

In [30]:
np.mean(np.random.randn(4,5))

np.float64(-0.019697774511711418)

In [32]:
np.std(np.random.randn(4,5))

np.float64(0.9045418165921267)

In [34]:
numbers=np.arange(10,100,50)

In [35]:
numbers.argmax()

np.int64(1)

In [36]:
numbers.max()

np.int64(60)

In [39]:
learning_rate=np.linspace(0,1,15)
learning_rate

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [40]:
np.random.randint(10,150,5)

array([ 28,  34, 103, 146, 149], dtype=int32)